/**
 * Action types
 */
export const BUS_STOPS_FETCH = 'BUS_STOPS_FETCH';
export const BUS_STOPS_FETCH_SUCCESS = 'BUS_STOPS_FETCH_SUCCESS';
export const BUS_STOPS_FETCH_FAILURE = 'BUS_STOPS_FETCH_FAILURE';
export const BUS_STOPS_FILTER = 'BUS_STOPS_FILTER';
export const BUS_STOP_SET_SELECTED = 'BUS_STOP_SET_SELECTED';
export const BUS_STOP_FETCH = 'BUS_STOP_FETCH';
export const BUS_STOP_FETCH_SUCCESS = 'BUS_STOP_FETCH_SUCCESS';
export const BUS_STOP_FETCH_FAILURE = 'BUS_STOP_FETCH_FAILURE';
